#! /bin/sh

# Reinitialise Pywal config
wal -R &

# Start the polybar
killall "polybar"
polybar bar &

# Set the pointer to be a normal pointer
xsetroot -cursor_name left_ptr &

# Start the compositor
killall "picom"
picom -b &

# Start the notification engine
killall "dunst"
dunst &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# colours
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config top_padding 27
bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
